### ISSUE TITLE
No handler defined for action

### ISSUE THREAD

**Issue by 58bits** [sanity-io/orderable-document-list#13]
Not sure what's up, whether it's something at our end but we have everything working - except the actions in the drop down menu....

![image](https://user-images.githubusercontent.com/405612/148933249-3cfd95b7-73db-4473-8a10-79da7fd84844.png)

Trying to Create a New Team Member, Show Increments, or Reset Order, shows the following console errors...

`No handler defined for action: undefined`
`No handler defined for action: showIncrements`
`No handler defined for action: resetOrder`

Our desk structure is...

```
import S from '@sanity/desk-tool/structure-builder'
import { orderableDocumentListDeskItem } from '@sanity/orderable-document-list'

export default () =>
  S.list()
    .title('Base')
    .items([
      // ...S.documentTypeListItems(),
      S.documentTypeListItem('post'),
      S.documentTypeListItem('author'),
      S.documentTypeListItem('category'),
      orderableDocumentListDeskItem({
        type: 'team_member',
        title: 'Team Members',
      }),
    ])
```

And  our schema for team_members...

```
import {
  orderRankField,
  orderRankOrdering,
} from '@sanity/orderable-document-list'

export default {
  name: 'team_member',
  title: 'Team Member',
  type: 'document',
  // Optional: The plugin also exports a set of 'orderings' for use in other Document Lists
  orderings: [orderRankOrdering],
  fields: [
    // Minimum required configuration
    orderRankField({ type: 'team_member' }),
    {
      name: 'name',
      title: 'Name',
      type: 'string',
    },
    {
      name: 'qualifications',
      title: 'Qualifications',
      type: 'string',
      options: {
        maxLength: 96,
      },
    },
    {
      name: 'position',
      title: 'Position',
      type: 'string',
      options: {
        maxLength: 96,
      },
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'name',
        maxLength: 96,
      },
    },
    {
      name: 'image',
      title: 'Image',
      type: 'image',
      options: {
        hotspot: true,
      },
    },
    {
      name: 'bio',
      title: 'Bio',
      type: 'array',
      of: [
        {
          title: 'Block',
          type: 'block',
          styles: [{ title: 'Normal', value: 'normal' }],
          lists: [],
        },
      ],
    },
  ],
  preview: {
    select: {
      title: 'name',
      media: 'image',
    },
  },
}
```

**Comment by SimeonGriggs** [comment]
Thanks for reporting, what version of the Studio are you using? We've seen this error in earlier versions but it should be fixed on at least 2.23.0 and above?

**Comment by 58bits** [comment]
Hi @SimeonGriggs  - thanks for the reply.

I using  version 2.23.3 of the Sanity CLI (as this the same as the version of Studio?)

**Comment by SimeonGriggs** [comment]
Can you also try updating the plugin to `0.0.4`?

**Comment by 58bits** [comment]
HIi@SimeonGriggs - I believe I'm already using 0.0.4 version of the plugin...

`"@sanity/orderable-document-list": "^0.0.4",`

Best,

Tony

**Comment by SimeonGriggs** [comment]
Hey! Turns out this was in issue in the Studio, which was [fixed in yesterday's 2.25.0 release](https://github.com/sanity-io/sanity/pull/3081) 🎉 

Upgrade your Studio to fix.

**Comment by 58bits** [comment]
@SimeonGriggs - okay thanks - I'll give it a try!

**Comment by 58bits** [comment]
@SimeonGriggs  - sorry - but still no luck. The same error, as well as new React errors `The input component for type "team_member" has no associated ref element. Please check the implementation of "Unknown"`

**Comment by SimeonGriggs** [comment]
Just to be completely sure, can you nuke your `node_modules` and `package-lock.json` and reinstall with latest-everything?

**Comment by 58bits** [comment]
Hi @SimeonGriggs  - that did it! Thank you! The UI updated as well. I'm still getting a `The input component for type "team_member" has no associated ref element. Please check the implementation of "Unknown" [` error message in the console, but I'll take a look at this separately. Thanks for the help.

**Comment by SimeonGriggs** [comment]
Excellent.

Well, other than that other error. I'll take a look at that. Feel free to file a new Issue.
